# Generated by Django 5.0.6 on 2025-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_uploadedimage_confidence_uploadedimage_prediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_history_skin_disorders", models.IntegerField()),
                ("family_history_depigmentation", models.IntegerField()),
                ("personal_history_autoimmune", models.IntegerField()),
                ("family_score", models.IntegerField()),
            ],
        ),
    ]
