# Generated by Django 5.0.6 on 2025-01-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_diethistory_lifestyleassessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PsychologicalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stress_anxiety", models.IntegerField(default=0)),
                ("grief_sadness", models.IntegerField(default=0)),
                ("anger_frustration", models.IntegerField(default=0)),
                ("mental_exhaustion", models.IntegerField(default=0)),
                ("guilt_distress", models.IntegerField(default=0)),
                ("family_work_conflicts", models.IntegerField(default=0)),
                ("disrespectful_behavior", models.IntegerField(default=0)),
                ("unethical_actions", models.IntegerField(default=0)),
                ("taking_from_others", models.IntegerField(default=0)),
                ("stressful_events", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
            ],
        ),
    ]
