# Generated by Django 5.0.6 on 2025-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_psychologicalassessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitiligoAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question1", models.IntegerField(default=0)),
                ("question2", models.IntegerField(default=0)),
                ("question3", models.IntegerField(default=0)),
                ("question4", models.IntegerField(default=0)),
                ("question5", models.IntegerField(default=0)),
                ("question6", models.IntegerField(default=0)),
                ("question7", models.IntegerField(default=0)),
                ("question8", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
            ],
        ),
    ]
