# Generated by Django 5.0.6 on 2025-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_vitiligoassessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chemical_exposure", models.IntegerField(default=0)),
                ("polluted_area", models.IntegerField(default=0)),
                ("harsh_chemicals", models.IntegerField(default=0)),
                ("sunlight_exposure", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
            ],
        ),
    ]
