# Generated by Django 5.0.6 on 2025-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_environmentalassessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sour_foods", models.JSONField(default=list)),
                ("salty_foods", models.JSONField(default=list)),
                ("processed_foods", models.JSONField(default=list)),
                ("incompatible_combinations", models.JSONField(default=list)),
                ("food_habits", models.JSONField(default=list)),
                ("oily_foods", models.JSONField(default=list)),
                ("meals_before_digestion", models.BooleanField(default=False)),
                ("diet_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="DietHistory",
        ),
    ]
