# Generated by Django 5.0.6 on 2025-01-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_dietassessment_delete_diethistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitiligoQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_spots", models.JSONField(blank=True, default=list)),
                ("hand_feet_spots", models.JSONField(blank=True, default=list)),
                ("arms_legs_spots", models.JSONField(blank=True, default=list)),
                ("depigmentation", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
