# Generated by Django 5.0.6 on 2025-01-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="grayscale",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="heatmap",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="wood_lamp",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
