# Generated by Django 5.0.6 on 2025-01-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_uploadedimage_grayscale_uploadedimage_heatmap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="predicted_val",
            field=models.IntegerField(null=True),
        ),
    ]
