# Generated by Django 5.0.6 on 2025-01-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_remove_uploadedimage_predicted_val"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
