# Generated by Django 5.0.6 on 2025-01-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_alter_patient_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together=set(),
        ),
    ]
