# Generated by Django 5.0.6 on 2025-01-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_alter_patient_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
