# Generated by Django 5.0.6 on 2025-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_alter_patient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
