# Generated by Django 5.0.6 on 2025-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_alter_patient_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="assessment_date",
            field=models.DateField(null=True),
        ),
    ]
