# Generated by Django 5.0.6 on 2025-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_alter_patient_assessment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="assessment_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
