# Generated by Django 5.0.6 on 2025-01-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0020_alter_patient_assessment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
