# Generated by Django 5.0.6 on 2025-01-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_contactsubmission_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyhistory",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.patient",
            ),
        ),
    ]
