# Generated by Django 5.0.6 on 2025-01-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0026_familyhistory_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familyhistory",
            name="patient",
        ),
    ]
